// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartTimer(arg1, arg2) {
  return window['go']['main']['App']['StartTimer'](arg1, arg2);
}

export function StartTotalTime() {
  return window['go']['main']['App']['StartTotalTime']();
}
