// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssociateProjectToWorkTime(arg1) {
  return window['go']['main']['App']['AssociateProjectToWorkTime'](arg1);
}

export function CalculateAndSaveProjectCost(arg1, arg2) {
  return window['go']['main']['App']['CalculateAndSaveProjectCost'](arg1, arg2);
}

export function CalculateWorkTimeForDay(arg1) {
  return window['go']['main']['App']['CalculateWorkTimeForDay'](arg1);
}

export function ChangeProjectClose(arg1) {
  return window['go']['main']['App']['ChangeProjectClose'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function EndBreak() {
  return window['go']['main']['App']['EndBreak']();
}

export function FinishDay() {
  return window['go']['main']['App']['FinishDay']();
}

export function GetAllProjects(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetAllProjects'](arg1, arg2, arg3, arg4, arg5);
}

export function GetDaySummary(arg1) {
  return window['go']['main']['App']['GetDaySummary'](arg1);
}

export function GetProjectByID(arg1) {
  return window['go']['main']['App']['GetProjectByID'](arg1);
}

export function GetStartTimes() {
  return window['go']['main']['App']['GetStartTimes']();
}

export function GetUnfinishedWorkTimeProjectWithoutSendingError() {
  return window['go']['main']['App']['GetUnfinishedWorkTimeProjectWithoutSendingError']();
}

export function RemoveTimer(arg1) {
  return window['go']['main']['App']['RemoveTimer'](arg1);
}

export function StartDay() {
  return window['go']['main']['App']['StartDay']();
}

export function StartTimer(arg1, arg2) {
  return window['go']['main']['App']['StartTimer'](arg1, arg2);
}

export function StartWorkTime() {
  return window['go']['main']['App']['StartWorkTime']();
}

export function TakeBreak() {
  return window['go']['main']['App']['TakeBreak']();
}

export function UpdateBreakTimeDuration(arg1, arg2) {
  return window['go']['main']['App']['UpdateBreakTimeDuration'](arg1, arg2);
}

export function UpdateProjectName(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectName'](arg1, arg2);
}

export function UpdateWorkTimeDuration(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkTimeDuration'](arg1, arg2);
}

export function UpdateWorkTimeProjectDuration(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkTimeProjectDuration'](arg1, arg2);
}
