// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssociateProjectToWorkTime(arg1) {
  return window['go']['main']['App']['AssociateProjectToWorkTime'](arg1);
}

export function CalculateAndSaveProjectCost(arg1, arg2) {
  return window['go']['main']['App']['CalculateAndSaveProjectCost'](arg1, arg2);
}

export function CalculateWorkTimeForDay(arg1) {
  return window['go']['main']['App']['CalculateWorkTimeForDay'](arg1);
}

export function ChangeProjectClose(arg1) {
  return window['go']['main']['App']['ChangeProjectClose'](arg1);
}

export function CloseResolutionTracker(arg1) {
  return window['go']['main']['App']['CloseResolutionTracker'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateResolutionUnit(arg1) {
  return window['go']['main']['App']['CreateResolutionUnit'](arg1);
}

export function CreateTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2, arg3);
}

export function EndBrb() {
  return window['go']['main']['App']['EndBrb']();
}

export function EndBreak() {
  return window['go']['main']['App']['EndBreak']();
}

export function FindResolutionTrackerByDay(arg1) {
  return window['go']['main']['App']['FindResolutionTrackerByDay'](arg1);
}

export function FinishDay() {
  return window['go']['main']['App']['FinishDay']();
}

export function GetAllProjects(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetAllProjects'](arg1, arg2, arg3, arg4, arg5);
}

export function GetCurrentActiveTimers() {
  return window['go']['main']['App']['GetCurrentActiveTimers']();
}

export function GetDaySummary(arg1) {
  return window['go']['main']['App']['GetDaySummary'](arg1);
}

export function GetOrCreateTodayResolutionTracker() {
  return window['go']['main']['App']['GetOrCreateTodayResolutionTracker']();
}

export function GetProjectByID(arg1) {
  return window['go']['main']['App']['GetProjectByID'](arg1);
}

export function GetStartTimes() {
  return window['go']['main']['App']['GetStartTimes']();
}

export function GetUnfinishedWorkTimeProjectWithoutSendingError() {
  return window['go']['main']['App']['GetUnfinishedWorkTimeProjectWithoutSendingError']();
}

export function GetUnitsByResolutionTracker(arg1) {
  return window['go']['main']['App']['GetUnitsByResolutionTracker'](arg1);
}

export function GetUnitsTrackerByDay(arg1) {
  return window['go']['main']['App']['GetUnitsTrackerByDay'](arg1);
}

export function RemoveTimer(arg1) {
  return window['go']['main']['App']['RemoveTimer'](arg1);
}

export function ResolveResolutionUnit(arg1) {
  return window['go']['main']['App']['ResolveResolutionUnit'](arg1);
}

export function StartDay() {
  return window['go']['main']['App']['StartDay']();
}

export function StartTimer(arg1, arg2) {
  return window['go']['main']['App']['StartTimer'](arg1, arg2);
}

export function StartWorkTime() {
  return window['go']['main']['App']['StartWorkTime']();
}

export function TakeBrb() {
  return window['go']['main']['App']['TakeBrb']();
}

export function TakeBreak() {
  return window['go']['main']['App']['TakeBreak']();
}

export function UpdateBrbDuration(arg1, arg2) {
  return window['go']['main']['App']['UpdateBrbDuration'](arg1, arg2);
}

export function UpdateBreakTimeDuration(arg1, arg2) {
  return window['go']['main']['App']['UpdateBreakTimeDuration'](arg1, arg2);
}

export function UpdateProjectName(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectName'](arg1, arg2);
}

export function UpdateResolutionTrackerCategory(arg1, arg2) {
  return window['go']['main']['App']['UpdateResolutionTrackerCategory'](arg1, arg2);
}

export function UpdateWorkTimeDuration(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkTimeDuration'](arg1, arg2);
}

export function UpdateWorkTimeProjectDuration(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkTimeProjectDuration'](arg1, arg2);
}
