name: Build and Publish Wails App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Install Wails
      run: |
        go install github.com/wailsapp/wails/cmd/wails@latest
        
    - name: Build Wails App
      run: wails build
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: wails-app
        path: build
        
  publish:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: wails-app
        
    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          *.exe
          *.dmg
          *.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
