name: Build and Publish Wails App
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # This will trigger the workflow on version tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
        
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm install
        
    - name: Build Frontend
      run: |
        cd frontend
        npm run build
        
    - name: Build Wails App (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        wails build -platform windows/amd64
        
    - name: Build Wails App (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
        wails build -platform darwin/universal
        
    - name: Build Wails App (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        wails build -platform linux/amd64
        
    - name: Upload Artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build/bin/*.exe
        
    - name: Upload Artifact (MacOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: build/bin/*.app
        
    - name: Upload Artifact (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: build/bin/*
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write  # This is important for creating releases
    
    steps:
    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-build
        path: windows
        
    - name: Download MacOS Artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-build
        path: macos
        
    - name: Download Linux Artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-build
        path: linux
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          windows/**
          macos/**
          linux/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
